#ifndef ROKAE_XMATE3_ROS2_RUNTIME_OWNER_ARBITER_HPP
#define ROKAE_XMATE3_ROS2_RUNTIME_OWNER_ARBITER_HPP

#include "rokae_xmate3_ros2/runtime/owner_arbiter.hpp"

#endif  // ROKAE_XMATE3_ROS2_RUNTIME_OWNER_ARBITER_HPP
