FROM ros:humble-ros-base

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-vcstool \
    libeigen3-dev \
    gazebo \
    ros-humble-gazebo-ros-pkgs \
    ros-humble-gazebo-ros2-control \
 && rm -rf /var/lib/apt/lists/*

RUN rosdep init 2>/dev/null || true && rosdep update
