---
bool success
string message
bool connected
bool power_on
bool drag_mode
bool simulation_mode
bool collision_detection_enabled
int32 motion_mode
uint8 operate_mode
int32 rt_mode
float64[6] joint_position
float64[6] joint_velocity
float64[6] joint_torque
float64[6] base_frame
string tool_name
string wobj_name
float64[] tool_pose
float64[] wobj_pose
float64 tool_mass
float64[3] tool_com
string backend_mode
string active_profile
string runtime_phase
string control_owner
string rt_subscription_plan
string profile_capability_summary
string runtime_option_summary
string planning_capability_summary
string model_exactness_summary
string catalog_provenance_summary
