function(rokae_load_runtime_host_policy policy_file)
  if(NOT EXISTS "${policy_file}")
    message(FATAL_ERROR "runtime host policy file not found: ${policy_file}")
  endif()

  file(STRINGS "${policy_file}" _policy_lines)
  foreach(_line IN LISTS _policy_lines)
    string(STRIP "${_line}" _line)
    if(_line STREQUAL "" OR _line MATCHES "^#")
      continue()
    endif()
    string(FIND "${_line}" "=" _eq_index)
    if(_eq_index LESS 1)
      continue()
    endif()
    string(SUBSTRING "${_line}" 0 ${_eq_index} _key)
    math(EXPR _value_index "${_eq_index} + 1")
    string(SUBSTRING "${_line}" ${_value_index} -1 _value)
    string(STRIP "${_key}" _key)
    string(STRIP "${_value}" _value)
    set(${_key} "${_value}" PARENT_SCOPE)
  endforeach()
endfunction()
