# ========================================
# xMate3 MoveIt2 Controllers Manager Configuration
# ========================================

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - xmate_joint_1
      - xmate_joint_2
      - xmate_joint_3
      - xmate_joint_4
      - xmate_joint_5
      - xmate_joint_6
